name: Bing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t bing-runner .

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run BingRewards Container with Logging
        run: |
          docker run -t -d --name bing-rewards \
          -v ${{ github.workspace }}/logs:/bing-rewards/BingRewards/logs \
          bing-runner python setup.py -e ${{ secrets.BING_EMAIL }} -p ${{ secrets.BING_PASSWORD }}

      - name: Run python script in Container
        run: |
          docker exec bing-rewards python BingRewards.py -nsb

      - name: Generate README.md
        run: |
          echo "# Bing Rewards Logs" > README.md
          echo "Logs can be found in the mounted directory." >> README.md
          echo "To mount logs, use the following command in your local setup:" >> README.md
          echo "```bash" >> README.md
          echo "docker run -v <absolute-path-to-logs-directory>:/bing-rewards/BingRewards/logs bing-runner" >> README.md
          echo "```" >> README.md
          
          if compgen -G "logs/*.log" > /dev/null; then
            for log in logs/*.log; do
              echo "## $(basename $log)" >> README.md
              echo "\`\`\`" >> README.md
              cat "$log" >> README.md
              echo "\`\`\`" >> README.md
            done
          else
            echo "No log files found." >> README.md
          fi

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with logs" || echo "No changes to commit"
          git push
